config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  resources :users, except: [:new, :create, :destroy]

  resources :posts do
    post "like" => "likes#create"
    delete "/like" => "likes#destroy"
  end

  resources :users do
    get "likes" => "users#likes"
    get "mycomments"=> "users#comments"
  end

  get "/" => "home#top"
  get "about" => "home#about"
  get "check" => "home#check"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, {presence: true, length: {maximum: 140}}
  validates :user_id, {presence: true}

  has_many :likes

  def user
    return User.find_by(id: self.user_id)
  end

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def posts
    return Post.where(user_id: self.id)
  end

  has_many :likes, dependent: :destroy
  has_many :like_posts, through: :likes, source: :post

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  def after_sign_in_path_for(resource)
    edit_user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end

  def check
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_like

  def create
    post = Post.find(params[:post_id])
    @like = Like.create(user_id: current_user.id, post_id: post.id)
  end

  def destroy
    post = Post.find(params[:post_id])
    like = Like.find_by(user_id: current_user.id, post_id: post.id)
    like.delete
  end

  private
  def set_like
    @post = Post.find(params[:post_id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_current_user, {only: [:edit, :destroy, :update]}

  def index
    @search_post = Post.search(params[:q])
    @search_user = User.search(params[:q])
    @posts = @search_post.result
    @users = @search_user.result
  end

  def show
    @post = Post.find_by(id: params[:id])
    @user = @post.user
    @likes_count = Like.where(post_id: @post.id).count
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(
      content: params[:content],
      user_id: current_user.id
    )

    if @post.save
      flash[:notice] = "投稿しました！"
      redirect_to(posts_path)
    else
      render action: :new
    end
  end

  def edit
    @post = Post.find_by(id: params[:id])
  end

  def update
    @post = Post.find_by(id: params[:id])
    @post.content = params[:content]
    if @post.save
      flash[:notice] = "編集完了"
      redirect_to(posts_path)
    else
      render action: :edit
    end
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    @post.destroy!
    flash[:notice] = "投稿削除完了"
    redirect_to(posts_path)
  end

  def ensure_current_user
    @post = Post.find_by(id: params[:id])
    if @post.user_id != current_user.id
      flash[:notice] = "自分の投稿のみ編集・削除ができます"
      redirect_to(posts_path)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_current_user, {only: [:edit, :update]}

  def index
    @search_user = User.search(params[:q])
    @users = @search_user.result
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def update
    @user = User.find_by(id: params[:id])
    @user.name = params[:name]
    @user.email = params[:email]

    if params[:image]
      @user.image_name = "#{@user.id}.jpg"
      image = params[:image]
      File.binwrite("public/user_images/#{@user.image_name}", image.read)
    end

    if @user.save
      flash[:notice] = "飼主変更完了！"
      redirect_to(user_path(@user.id))
    else
      render action: :edit
    end
  end

  def comments
    @user = User.find_by(id: params[:user_id])
  end

  def likes
    @user = User.find_by(id: params[:user_id])
    @likes = Like.where(user_id: @user.id)
  end

  def ensure_current_user
    if current_user.id != params[:id].to_i
      flash[:notice] = "本人のみ編集ができます"
      redirect_to(posts_path)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/about.html.erb
<div class="about-all">
  <div class="about-top">
  <h1 class="p-5 mb-1 text-center text-success font-weight-bold">〜WANCHATとは〜</h1>
  </div>
    <div class="about-content">
    <p class="p-5 mb-1 text-center font-weight-bold">ご自慢の愛犬を投稿し、犬好きのたくさんの人達と<br>共感を得てコミュニケーションが取れる場となっております。</p>
    <p class="p-5 mb-1 text-center font-weight-bold">癒しの場として使うことも出来ますし、<br>この先にどんな犬を飼おうか迷っている方はこのサイトを使って<br>参考にすることができますので是非ご利用ください</p>
    </div>
</div>

app/views/home/check.html.erb
<div class="check-all">
  <div class="check-top">
    <h1 class="p-5 mb-1 text-center text-success font-weight-bold">〜なぜワンチャットを作ったのか？〜</h1>
  </div>
    <div class="check-content">
      <p class="p-5 mb-1 text-center font-weight-bold">私自身犬が大好きで他の人の飼っているペットを見て見たいというのと<br>2020年7月10日に18歳の愛犬が他界に行ってしまい、<br>愛犬を失う辛さを知っているので悲しんでぽっかりと心が空いている人たちの<br>励みになるように作成しました。
      <p class="p-5 mb-1 text-center font-weight-bold">その他にも、これから犬を飼いたいけど犬種がわからない<br>飼ってみての感想を聞いてみたい人など<br>いると思ったのでその方々のお役に立てると思いました。</p>
    </div>
</div>

app/views/home/top.html.erb
<div class="top-main">
  <p class="p-1 mb-1 text-center text-success font-weight-bold">心の癒しとコミュニケーション</p>
  <div class="top-message">
    <p class="text-center font-weight-bold">〜世界に一匹のペットを世界に広めよう〜</p>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div id="footer">
  <p>made by Kazuya Kojima</p>
</div>

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
  <div class="d-flex">
    <div class="font-weight-bold p-3">
      <%= link_to("投稿画面へ", posts_path)%>
    </div>
    <div class="font-weight-bold p-3">
      <%= link_to("新規投稿", new_post_path)%>
    </div>
    <div class="font-weight-bold p-3">
      <%= link_to("飼主一覧", users_path)%>
    </div>
    <div class="font-weight-bold p-3">
      <%= link_to("マイページ", user_path(current_user.id))%>
    </div>
    <div class="font-weight-bold p-3">
      <%= link_to("ログアウト", destroy_user_session_path, method: :delete)%>
    </div>
  </div>

<% else %>
  <div class="d-flex">
    <div class="font-weight-bold p-3">
      <%= link_to("WANCHAT", "/")%>
    </div>

    <div class="font-weight-bold p-3">
      <%= link_to("WANCHATとは", about_path)%>
    </div>

    <div class="font-weight-bold p-3">
      <%= link_to("なぜ作ったのか", check_path)%>
    </div>

    <div class="font-weight-bold p-3">
      <%= link_to("新規飼主",new_user_registration_path, class: 'post')%>
    </div>

    <div class="font-weight-bold p-3">
      <%= link_to("ログイン",new_user_session_path, class: 'post')%>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WanChat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">

  </head>

  <body>
    <header>
      <%= render "layouts/header" %>
    </header>
    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="flash">
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
    <footer>
      <%= render "layouts/footer" %>
    </footer>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

app/views/likes/_like.html.erb
<% if post.liked_by?(current_user) %>
   <%= link_to(post_like_path(post), method: :delete, remote: true, id: "like-btn-#{post.id}") do %>
       <i class="fa-lg fas fa-heart icon-btn liked heart_red"></i>
   <% end %>
<% else %>
   <%= link_to(post_like_path(post), method: :post, remote: true, id: "like-btn-#{post.id}") do %>
       <i class="fa-lg far fa-heart"></i>
   <% end %>
<% end %>

app/views/likes/create.js.erb
$('#like-btn-<%= @post.id %>').html("<%= escape_javascript(render partial: "likes/like", locals: { post: @post }) %>");

app/views/likes/destroy.js.erb
$('#like-btn-<%= @post.id %>').html("<%= escape_javascript(render partial: "likes/like", locals: { post: @post }) %>");

app/views/posts/edit.html.erb
<div class="all-posts-edit">
  <div class="content-posts-edit font-weight-bold text-center">
    <h1>〜編集〜</h1>
  </div>
    <%= form_tag(post_path(@post.id), method: :patch) do %>
      <div class="posts-edit-error text-center">
        <% @post.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      </div>
          <div class="posts-edit-textarea text-center">
            <textarea name="content"><%= @post.content %></textarea>
          </div>
            <div class="posts-edit-button text-center">
              <br><input type="submit" value="更新">
            </div>
    <% end %>
  </div>

app/views/posts/index.html.erb
<div class="all-posts-index">
  <h1 class="text-center font-weight-bold p-3 text-success">〜投稿一覧〜</h1>
  <%= search_form_for @search_user do |f| %>
    <div class="field-owner">
      <%= f.label :name_cont, "飼主検索：" %>
      <%= f.text_field :name_cont %>
      <%= f.submit %>
    </div>
  <% end %>

  <%= search_form_for @search_post do |f| %>
    <div class="field-content">
      <%= f.label :content_cont, "内容検索：" %>
      <%= f.text_field :content_cont %>
      <%= f.submit %>
    </div>
  <% end %>


  <% @posts.each do |post|%>
    <div class="content-posts-index font-weight-bold">
      <div class="posts-user-photo">
        <img src="<%= "/user_images/#{post.user.image_name}" %>">
      </div>
      <div class="posts-user-content">
        <p>飼主：<%= link_to(post.user.name, user_path(post.user.id)) %></p>
        <p>内容：<%= link_to(post.content, post_path(post.id))%></p>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="all-posts-new">
  <div class="content-posts-new font-weight-bold text-center">
    <h1>〜WANCHATな投稿をしましょう！〜</h1>
    <p>ex）このアイコンは、ミニチュアダックスの○○○ちゃんが餌を食べている写真です。<br>この写真は、ゴールデンレトリバーの○○○君です。大型犬はおすすめなのでぜひ買ってみてください！など...</p>
  </div>
    <%= form_tag(posts_path) do %>
      <div class="posts-new-error text-center font-weight-bold">
        <% @post.errors.full_messages.each do |message| %>
          <p>＊<%= message %></p>
        <% end %>
      </div>

          <div class="posts-new-textarea text-center">
            <textarea name="content"><%= @post.content %></textarea>
          </div>
            <div class="posts-new-button text-center">
              <br><input type="submit" value="ワン！">
            </div>
    <% end %>
</div>

app/views/posts/show.html.erb
<div class="all-posts-show">
  <div class="posts-show-photo">
    <div class="content-posts-show font-weight-bold">
      <img src="<%= "/user_images/#{@user.image_name}" %>">
      <p>飼主：<%= link_to(@user.name, user_path(@user.id)) %></p>
      <p>コメント： <%= @post.content %></p>
      <p>時間： <%= l @post.created_at %></p>
      <div id="like-btn-<%= @post.id %>">
        <%= render 'likes/like', post: @post %>
      </div>
      <p><%= @likes_count %></p>
      <% if @post.user.id == current_user.id %>
        <%= link_to("(編集)", edit_post_path(@post.id)) %>
        <%= link_to("(削除)", post_path(@post.id), {method: :delete}) %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/comments.html.erb
<div class="all-users-show-second">
  <h1 class="text-center font-weight-bold p-3 text-success">〜マイコメント一覧〜</h1>
</div>
<% @user.posts.each do |post| %>
  <div class="content-posts-show font-weight-bold">
    <div class="posts-user-photo">
      <img src="<%= "/user_images/#{post.user.image_name}" %>">
    </div>
    <div class="posts-user-content">
      <p>飼主：<%= link_to(post.user.name, user_path(post.user.id)) %></p>
      <p>内容：<%= link_to(post.content, post_path(post.id))%></p>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="all-users-edit">
  <div class="users-edit-title">
    <h1 class="text-center font-weight-bold text-success">〜飼主編集〜</h1>
    <p class="text-center font-weight-bold p-2">※必ずご自分の愛犬または、お気に入りのワンチャンの画像を設定してください！</p>
  </div>
  <div class="users-edit-error text-center font-weight-bold">
    <% @user.errors.full_messages.each do |message| %>
      <p><%= message  %></p>
    <% end %>
  </div>

  <div class="users-edit-content text-center font-weight-bold">
    <%= form_tag(user_path(@user.id), method: :patch, multipart: true) do %>
      <p class="m-4">-画像-</p>
        <input name="image" type="file">
      <p class="font-weight-bold m-4">-飼主名-</p>
        <input name= "name" value="<%= @user.name %>">
      <p class="font-weight-bold m-4">-メールアドレス-</p>
        <input name="email" value="<%= @user.email %>">
          <div class="users-edit-button text-center m-4">
            <input type="submit" value="登録">
          </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="all-users-index">
  <h1 class="text-center font-weight-bold p-3 text-success">〜飼主一覧〜</h1>
  <%= search_form_for @search_user do |f| %>
    <div class="field-content">
      <%= f.label :name_cont, "飼主検索：" %>
      <%= f.text_field :name_cont %>
      <%= f.submit %>
    </div>
  <% end %>
    <% @users.each do |user| %>
      <div class="content-users-index font-weight-bold">
        <div class="user-photo">
          <img src="<%= "/user_images/#{user.image_name}" %>">
        </div>
        <div class="user-name-index">
          飼主：<%= link_to(user.name, user_path(user.id)) %>
        </div>
      </div>
    <% end %>
</div>

app/views/users/likes.html.erb
<div class="all-users-show-second">
  <h1 class="font-weight-bold">〜ハートを押した投稿一覧〜</h1>
</div>
<% @likes.each do |like| %>
  <% post = Post.find_by(id: like.post_id)%>
  <div class="content-posts-show font-weight-bold">
    <div class="posts-user-photo">
      <img src="<%= "/user_images/#{post.user.image_name}" %>">
    </div>
    <div class="posts-user-content">
      <p>飼主：<%= link_to(post.user.name, user_path(post.user.id)) %></p>
      <p>内容：<%= link_to(post.content, post_path(post.id))%></p>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="all-users-show">
  <h1 class="text-center font-weight-bold p-3 text-success">〜マイページ〜</h1><br>
    <div class="user-show-photo">
      <div class="content-users-show font-weight-bold">
        <img src="<%= "/user_images/#{@user.image_name}" %>">
        <p>飼主： <%= @user.name %><br></p>
        <p>メールアドレス： <%= @user.email %></p>
          <% if @user.id == current_user.id %>
            <div class="users-show-edit">
              <%= link_to("（編集）", edit_user_path) %>
            </div>
          <% end %>
      </div>
    </div>
</div>
  <h1 class="text-center">⬇️下記を閲覧したい場合クリック！⬇️</h1>
  <div class="all-users-show-second">
    <h2 class="font-weight-bold"><%=link_to("〜マイコメント一覧〜", user_mycomments_path(@user.id))%></h2>
  </div>
    <div class="all-users-show-second">
      <h2 class="font-weight-bold"><%=link_to("〜ハート押した投稿一覧〜", user_likes_path(@user.id)) %></h2>
    </div>